# Generated by Django 3.0 on 2021-04-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210428_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcome',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
