# Generated by Django 3.0 on 2021-04-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210428_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcome',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
