# Generated by Django 3.0 on 2021-04-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210428_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcome',
            name='title2_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
