# Generated by Django 3.0 on 2021-04-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_welcome_title2_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourstory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatweofferobjects',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
