# Generated by Django 3.0 on 2021-04-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_specialization_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='specializationitem',
            name='icon',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
