# Generated by Django 3.0 on 2021-04-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_ourrecentprojects_ourrecentprojectsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
