# Generated by Django 3.0 on 2021-05-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210504_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatweofferobjects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
