# Generated by Django 3.0 on 2021-05-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_whatweofferobjects_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatweofferobjects',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
