# Generated by Django 3.0 on 2021-05-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_services_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='client_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
