# Generated by Django 3.0 on 2021-05-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_services_client_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
