# Generated by Django 3.0 on 2021-05-08 08:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210508_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
