# Generated by Django 3.0 on 2021-05-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='description',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
