# Generated by Django 3.0 on 2021-05-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210512_0816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientsection',
            options={'verbose_name_plural': 'Client Section'},
        ),
    ]
