# Generated by Django 3.0 on 2021-05-12 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210512_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name_plural': 'Contact Info'},
        ),
        migrations.AlterModelOptions(
            name='ourrecentprojects',
            options={'verbose_name_plural': 'Our Recent Project'},
        ),
        migrations.AlterModelOptions(
            name='ourstory',
            options={'verbose_name_plural': 'Our Stories'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='whatweoffer',
            options={'verbose_name_plural': 'What We Offer'},
        ),
        migrations.AlterModelOptions(
            name='whatweofferobjects',
            options={'verbose_name_plural': 'What We Offer Object'},
        ),
    ]
