# Generated by Django 3.0 on 2021-05-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210512_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welcome',
            options={'verbose_name_plural': 'Welcome'},
        ),
    ]
