# Generated by Django 3.0 on 2021-05-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210512_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services_heading',
            options={'verbose_name_plural': 'Service Heading'},
        ),
    ]
